#!/bin/bash

progname=${0##*/}
version=0.55

read -rd '' usage <<END
Usage: $progname [-ilf] <in_file> [<out_file>]
       $progname -j|-J|-c [-espklf] [-m <num>] [-d <num>] <in_file> [<out_file>]
       $progname -x [-lf] <in_file> [<out_file>]
       $progname -h        (for help)
END

verstring="$progname version $version ($(date +%F -r "$0"))"

#-- help docs ----------------------------------------------

IFS= read -rd '' help_text <<END

Help on $verstring

This program exports facts (also called notes) from Anki
decks or deck collections in .apkg or .colpkg files.
There are 6 separate modes of operation:

        Info about the Anki file to show on screen
    -i  Info about the Anki file in JSON format
    -c  Extract facts as CSV files
    -j  Extract facts as compact JSON
    -J  Extract facts as verbose JSON
    -x  Dump all available data unchanged as JSON

Anki files may contain more than one deck or subdeck, and
usually contain more than one model. A "model" is a named
set of field names for the facts. When no options are used,
a numbered list of the decks and models in the Anki file are
shown. These numbers can then be used with the -d and -m
options to select the decks and models to export.

Be aware that each model can be used in more than one deck
or subdeck so selecting a single model with -m may not be
sufficient to select only one type of fact. In this case you
can also use the -d option to select the deck you want and
so avoid mixing different types of facts together. Also -p
adds the path of the subdeck to a "subdeck" field in every
fact so you can see which deck each fact came from.

Note that options -m -d -e -s -p -k described below only
work in the fact extraction modes -j -J -c.


SYNOPSIS:

$(sed 's/^\S* */    /' <<<"$usage")


OPTIONS:

        Info mode is when there are no options. It lists the
        decks and models present in the given <in_file>.

    -i  Info mode in JSON format. Outputs a JSON version of
        the file info instead of the human readable version.

    -c  Output facts as CSV files. CSV is the best format
        for import into a spreadsheet for example. Facts for
        each model are written to separate CSV files with
        field names on the first line like this:

        "field name 1","field name 2","field name 3"
        "fact 1 value 1","fact 1 value 2","fact 1 value 3"
        "fact 2 value 1","fact 2 value 2","fact 2 value 3"
        "fact 3 value 1","fact 3 value 2","fact 3 value 3"

    -j  Output facts as a JSON object (compact style).
        The field names are written once only, and the
        fact values are written as arrays of strings.

        {
          "model 1": {
            "fields": ["field name 1", "field name 2", "field name 3"],
            "facts": [
              ["fact 1 value 1", "fact 1 value 2", "fact 1 value 3"],
              ["fact 2 value 1", "fact 2 value 2", "fact 2 value 3"]
            ]
          }
        }

    -J  Output facts as a JSON object (verbose style).
        Like -j except the field names are the keys of every
        fact object, instead of a list of fields just once.

        {
          "model 1": [
            {
              "field name 1": "fact 1 value 1",
              "field name 2": "fact 1 value 2"
              "field name 3": "fact 1 value 3"
            },
            {
              "field name 1": "fact 2 value 1",
              "field name 2": "fact 2 value 2"
              "field name 3": "fact 2 value 3"
            }
          ]
        }

    -s  Simplify and separate the JSON outputs for each
        model instead of a combined JSON object for all
        models keyed on model name. Useful when -m is used
        to select a single model and you just want the facts
        themselves. So -js outputs objects like this:

        {
          "fields": ["field name 1", "field name 2", "field name 3"],
          "facts": [
            ["fact 1 value 1", "fact 1 value 2", "fact 1 value 3"],
            ["fact 2 value 1", "fact 2 value 2", "fact 2 value 3"]
          ]
        }

        and -Js outputs an array of objects like this:

        [
          {
            "field name 1": "fact 1 value 1",
            "field name 2": "fact 1 value 2"
            "field name 3": "fact 1 value 3"
          },
          {
            "field name 1": "fact 2 value 1",
            "field name 2": "fact 2 value 2"
            "field name 3": "fact 2 value 3"
          }
        ]

    -m <num>
        Choose the model number <num> to extract instead of
        extracting all models. The <num> is a model number
        as listed by info mode. More than one <num> may be
        comma separated.

    -d <num>
        Choose the deck number <num> to extract instead of
        extracting all decks. The <num> is a deck number
        as listed by info mode. More than one <num> may be
        comma separated. All subdecks of the given deck are
        also included unless you also use the -e option.

    -e  Exact deck number. Only output facts with cards in
        the exact deck given in the -d option. So it does
        not automatically include all subdecks.

    -p  Include path (eg. deck::subdeck::subsubdeck) of the
        subdeck in a "subdeck" field. Note: If a fact is
        used by cards in more than one deck, then only the
        alphabetically first subdeck path is included.

    -k  Keep HTML tags and entities in data. By default
        HTML tags are removed and HTML entities converted.

    -f  Force overwrite of existing files. By default a
        warning is shown and files are not overwritten.

    -x  Dump JSON equivalent of all data in the Anki file
        with minimal processing. Useful for debugging.

    -l  Use 'less' pager to display output neatly formatted
        instead of saving files on disk or sending minimal
        JSON to stdout. Useful for visualising what the
        output will be before actually making files.

    -V  Display program version and exit.

    -h  Display this help and exit.


DESCRIPTION:

The <in_file> is the Anki deck or collection from which to
extract information, and <out_file> is the file in which to
place the output, or the prefix path on which to base output
filenames depending on the mode and options.

In -c CSV mode, facts from each model are saved to separate
CSV files using <out_file> as a prefix and the model name as
suffix. If no <out_file> is given then the <in_file> is used
as the prefix. If the <out_file> is - then all CSV data is
written to stdout, which is only useful if the deck and
model have been selected using -d and -m options.

Similarly, when -s is used with JSON modes -j -J then facts
from each model are saved to separate JSON files using
<out_file> as a prefix and the model name as suffix. If no
<out_file> is given then the <in_file> is used as the
prefix. If the <out_file> is - then a stream of JSON objects
is written to stdout without separating commas.

In the other modes -i -x and -j -J without -s, the output is
sent to stdout by default. If <out_file> is given, and it is
not - then output is saved to that <out_file> (possibly with
a different file extension to match the output type).

Note: From Anki version 2.1.50 onwards, the format of Anki's
saved decks changed. This program does not work with the
newer format. Fortunately, public shared decks on AnkiWeb
use the older format. When you export your own decks from
Anki you can tick the option "Support older Anki versions"
to get the older format this program needs.

Public shared Anki decks are available from:

    https://ankiweb.net/shared/decks


EXAMPLES:

To list the decks and models in an Anki deck file:

    \$ $progname mydeck.apkg

You can grep the output of the above command to quickly find
the number of a specific deck or model. Or you could display
the same information in the less pager with:

    \$ $progname -l mydeck.apkg

To display facts in JSON format neatly for viewing:

    \$ $progname -Jl mydeck.apkg

If you want to pipe the stream of JSON objects produced by
the -s option, which normally writes to a separate file for
each model, you must explicitly indicate that you want the
output to go to stdout by putting a - as the <out_file> like
this for example to pipe into jq:

    \$ $progname -Js -m1 mydeck.apkg -  | jq -s length

To extract all models as CSV files saved in a directory,
put a / on the end of the <out_file> like this:

    \$ $progname -c mydeck.apkg outdir/

To extract facts from many Anki files, use a bash for-loop:

    \$ for f in *.apkg; do $progname -js "\$f" myjson/; done

____________________________________________________________
END

# colour highlighting for on screen help
read -rd '' highlight <<'END'
s/\<($progname)\>/\x1b[1m\1\x1b[22m/g
s/(^|\W)(-\w+)/\1\x1b[1m\2\x1b[22m/g
s/<(\w+)>/<\x1b[36m\1\x1b[39m>/g
/^SYNOPSIS:/,+5 s/([^\x1b])([]<>|{}[]+)/\1\x1b[2m\2\x1b[22m/g
s/^( +)([]["{}].*)/\1\x1b[38;5;143m\2\x1b[39m/
s,\<https?://[A-Za-z0-9./-]+\>,\x1b[38;5;69m&\x1b[39m,g
/^ +\$/ s/\x1b\[[0-9;]*m//g
s/^( +)\$(.*)/\1\x1b[2m$\x1b[22m\x1b[38;5;143m\2\x1b[39m/
s/^[A-Z ]+:$/\x1b[1m&\x1b[22m/
END
highlight=${highlight//\$progname/$progname}

show_help() {
    if [[ -t 1 ]]; then
        sed -E "$highlight" | less -R
    else
        cat
    fi <<<"${help_text%$'\n'}"
}

#-- global variables ---------------------------------------

# already defined (see above):
# progname, version, usage, help_text, highlight

json_info=0         # -i
csv_out=0           # -c
json_compact=0      # -j
json_verbose=0      # -J
json_dump=0         # -x
text_info=0         # if none of the above
decks=()            # -d <num>
models=()           # -m <num>
exact_deck=0        # -e
separate=0          # -s
add_subdeck=0       # -p
keep_html=0         # -k
force=0             # -f
in_file=''          # input file
out_file=''         # output file or prefx for files
database=''         # current sqlite database
to_stdout=0         # whether output should go to stdout
to_less=0           # whether to display output in less
less_file=''        # temp file holds output for less
dids=''             # deck ids depending on -d -e
mids=''             # model ids depending on -m
declare -A tempfiles=() # track temp files so exit handler can tidy them up

#-- error functions ----------------------------------------

warn() {
    [[ -t 2 ]] && printf '\e[33m%s\e[39m\n' "$@" || printf '%s\n' "$@"
} >&2

die() {
    [[ -t 2 ]] && printf '\e[1;31m%s\e[22;39m\n' "$1" && shift
    (($#)) && printf '%s\n' "$@"
    exit 1
} >&2

debug_indent=''
debug() {
    if (($#)); then
        [[ -z $DEBUG ]] && return
        local opt=''
        [[ $1 == -[se] ]] && opt=$1 && shift
        [[ $opt == -e ]] && debug_indent=${debug_indent#    }
        printf '%s\n' "$@" | sed "s/^/$debug_indent/" >> "$DEBUG"
        [[ $opt == -s ]] && debug_indent="$debug_indent    "
    elif [[ -z $DEBUG ]]; then
        cat >> /dev/null
    else
        sed "s/^/$debug_indent> /" >> "$DEBUG"
    fi
}

#-- parse options ------------------------------------------

# nice way to display available letter options
# echo -e \\n {a..z} \\n {A..Z} \\n | sed 's/[hijJcdmespkflx]/\x1b[38;5;238m&\x1b[39m/g'

while getopts ':VhicjJm:d:espkflx-' OPT; do
    case $OPT in
    \?) die "Unknown option -$OPTARG" "$usage" ;;
    : ) die "Option -$OPTARG requires a value" "$usage" ;;
    - ) break ;;    # end of options -- mark
    V ) printf '%s\n' "$verstring"; exit ;;
    h ) show_help; exit ;;
    i ) json_info=1 ;;
    c ) csv_out=1 ;;
    j ) json_compact=1 ;;
    J ) json_verbose=1 ;;
    e ) exact_deck=1 ;;
    s ) separate=1 ;;
    p ) add_subdeck=1 ;;
    k ) keep_html=1 ;;
    f ) force=1 ;;
    l ) to_less=1 ;;
    x ) json_dump=1 ;;
    m | d ) [[ $OPTARG =~ ^[1-9][0-9]*(,[1-9][0-9]*)*$ ]] || \
        die "Option -$OPT requires a positive integer, or more than one separated by commas"
        IFS=, read -a arry <<<"$OPTARG" ;;&
    m ) models+=("${arry[@]}") ;;
    d ) decks+=("${arry[@]}") ;;
    esac
done
shift "$((OPTIND-1))"

(($#>2)) && die "Too many arguments" "$usage"
in_file=$1
out_file=$2

#-- sanity checks ------------------------------------------

# check dependencies
for dep in unzip sqlite3 jq file tput; do
    type -t "$dep" &>/dev/null || \
        die "$dep command is not available. Please install it first."
done

# check mode options
text_info=$((1-json_info-csv_out-json_compact-json_verbose-json_dump))
((text_info<0)) && die "Cannot use more than one of the mode options -i -c -j -J -x at the same time" "$usage"

# check export options
(( (${#models[@]} || ${#decks[@]} || exact_deck || separate || add_subdeck || keep_html) \
    && !(csv_out || json_compact || json_verbose) )) && \
    die "Cannot use any of -e -s -p -k -m -d unless exporting facts in one of the -j -J -c modes" "$usage"

# check input file
[[ -n $in_file ]] || die "Input filename required" "$usage"
[[ $in_file == *.apkg || $in_file == *.colpkg ]] || die "Input file not a *.apkg or *.colpkg file"
[[ -f $in_file ]] || die "Cannot find file: $in_file"
[[ -r $in_file ]] || die "Cannot read file: $in_file"
file -b "$in_file" | grep -q '^Zip archive' || die "Input file is not zipped: $in_file"
files=$(unzip -Z1 "$in_file")
grep -q 'collection\.anki' <<<"$files" || die "Input file is not an Anki deck: $in_file"
grep -q 'collection\.anki21$' <<<"$files" || die "Unsupported Anki deck format: $in_file"

# CSV mode must always write separate ouputs
((csv_out)) && separate=1

# find output location
if (($#==1 && separate)); then
    out_file=$(sed -E 's/\.(apkg|colpkg)$//I' <<<"$in_file")
elif (($#==1)) || [[ $out_file == - ]]; then
    to_stdout=1
elif [[ -z $out_file ]]; then
    out_file=$PWD
fi
if ((!to_stdout)); then
    if [[ $out_file == */ || -d $out_file ]]; then
        out_file=$(sed -E 's,/*$,,' <<<"$out_file")
        leafname=$(sed -E 's,.*/,,; s/\.(apkg|colpkg)$//I' <<<"$in_file")
        out_file+="/$leafname"
    else
        out_file=$(sed -E 's/\.(csv|json)$//I' <<<"$out_file")
    fi
fi

#-- helper functions ---------------------------------------

send_out() {
    local type=$1 model=$2 file=$out_file
    if ((to_less)) && [[ $type == json ]]; then
         jq -C .
    elif ((to_stdout || to_less)); then
        cat
    else
        ((separate)) && file+=" @ $model"
        file+=".$type"
        if ((!force)) && [[ -e $file ]]; then
            warn "Skipping existing file $file"
        else
            [[ $file == */* ]] && mkdir -p "${file%/*}"
            cat > "$file"
        fi
    fi
}

exithandler() {
    ((${#tempfiles[@]})) && rm -- "${!tempfiles[@]}" &> /dev/null
}
trap "exithandler" exit int

newtemp() {
    newtemp=$(mktemp -t "$progname.XXXX${1:+.}$1")
    tempfiles["$newtemp"]=1
}

rmtemp() {
    local f
    rm -- "$@" &> /dev/null
    for f in "$@"; do unset "tempfiles[$f]"; done
}

#-- big functions ------------------------------------------

get_info() {
    sqlite3 -json "$database" "
        select decks, models from col;
        select c.did, count(*) cards, group_concat(distinct n.mid) models
        from cards c join notes n on c.nid==n.id
        group by c.did;
        select n.mid, count(distinct n.id) facts, count(distinct c.did) decks
        from cards c join notes n on c.nid==n.id
        group by mid;
    " | jq -scM '
        (reduce .[1][] as $d ({};
            .[$d.did | tostring] = ($d |
            .models |= reduce split(",")[] as $mid ({}; .[$mid] = 1)
        ))) as $dk |
        (reduce .[2][] as $m ({}; .[$m.mid | tostring] = $m)) as $ml |
        {   decks: (
                .[0][0].decks | fromjson | map(
                    (.id | tostring) as $did |
                    if $dk | has($did)
                    then . + $dk[$did]
                    else . + {cards: 0, models: {}} end |
                    {name, cards, models, did: .id}
                ) | sort_by(.name) | to_entries | map({num: (.key+1)} + .value) |
                . as $dkcopy | map(
                    (.name + "::") as $pre | .models as $mod |
                    .totcards = (0 + reduce $dkcopy[] as $d (.cards;
                        if $d.name | startswith($pre)
                        then . + $d.cards
                        else . end)) |
                    .totmodels = (reduce $dkcopy[] as $d (.models;
                        if $d.name | startswith($pre)
                        then . + $d.models
                        else . end) | length) |
                    .models |= length |
                    {num, name, cards, models, totcards, totmodels, did}
                )
            ),
            models: (
                .[0][0].models | fromjson | [
                    .[] | (.id | tostring) as $mid |
                    if $ml | has($mid)
                    then . + $ml[$mid]
                    else . + {facts: 0, decks: 0} end |
                    {name, facts, decks, fields: (.flds | map(.name)), mid: .id}
                ] | sort_by(.name) | to_entries | map({num: (.key+1)} + .value)
            )
        }'
}

do_json_info() {
    get_info | jq -cM '
        .decks |= map(del(.did)) | .models |= map(del(.mid))
    ' | send_out json
}

do_text_info() {
    get_info | jq -r --argjson cols "$(tput cols)" '
        def pad($sz): " " * $sz + tostring | .[-$sz:];
        "", "DECKS:",
        (.decks[-1].num | log10 | floor + 1) as $sz |
        (.decks[] | "",
            "\(.num | pad($sz)). \(.name)",
            "\("" | pad($sz))  cards: \(.cards), models: \(.models)",
            if .cards != .totcards
            then "\("" | pad($sz))  cards: \(.totcards), models: \(.totmodels)    <--- total including subdecks"
            else empty end
        ),
        "", "MODELS:",
        (.models[-1].num | log10 | floor + 1) as $sz |
        ($cols - $sz - 10) as $width | (" " * ($sz + 10)) as $indent |
        (.models[] | "",
            "\(.num | pad($sz)). \(.name)",
            "\("" | pad($sz))  facts: \(.facts), decks: \(.decks)",
            "\("" | pad($sz))  fields: \(
                .fields | join(",\u001f") |
                gsub("(?<o>\\O{1,\($width)})\u001f"; "\(.o)\n") |
                split("\n") | map(gsub("\u001f"; " ")) |
                if length > 1 and (.[-2:] | map(length) | add) < $width
                then .[-2] += " " + .[-1] | del(.[-1])
                else . end | join("\n\($indent)")
            )"),
        ""
    ' | send_out txt
}

count_decks() {
    sqlite3 -json "$database" "select decks from col" | \
    jq -cr '.[0].decks | fromjson | length'
}

count_models() {
    sqlite3 -json "$database" "select models from col" | \
    jq -cr '.[0].models | fromjson | length'
}

get_dids() {
    ((${#decks[@]})) || return
    sqlite3 -json "$database" "select decks from col" | \
    jq -cr --argjson exact "$exact_deck" --arg nums "${decks[*]}" '
        ($nums | reduce split(" ")[] as $n ({}; .[$n] = 1)) as $nums |
        .[0].decks | fromjson | to_entries | map({name: .value.name, did: .key}) |
        sort_by(.name) | to_entries | map({num: (.key+1 | tostring)} + .value) |
        reduce .[] as $d ({}; .[$d.did] = $d) | . as $decks |
        with_entries(select(.value.num | in($nums))) |
        if $exact == 0
        then with_entries(
            (.value.name + "::") as $pre |
            ., ($decks | to_entries[] |
            select(.value.name | startswith($pre)))
        ) else . end |
        keys_unsorted | join(",")'
}

get_mids() {
    ((${#models[@]})) || return
    sqlite3 -json "$database" "select models from col" | \
    jq -cr --arg nums "${models[*]}" '
        ($nums | reduce split(" ")[] as $n ({}; .[$n] = 1)) as $nums |
        .[0].models | fromjson | to_entries | map({name: .value.name, mid: .key}) |
        sort_by(.name) | to_entries | map({num: (.key+1 | tostring)} + .value) |
        map(select(.num | in($nums)) | .mid) | join(",")'
}

get_facts() {
    local sql
    IFS= read -rd '' sql <<END
    select decks, models from col;
    select n.mid, n.flds, group_concat(c.did) dids
    from cards c join notes n on c.nid==n.id
    where
    group by n.id
    order by n.sfld;
END
    if [[ -n $dids && -n $mids ]]; then
        sql=$(sed "s/where/& c.did in ($dids) and n.mid in ($mids)/" <<<"$sql")
    elif [[ -n $dids ]]; then
        sql=$(sed "s/where/& c.did in ($dids)/" <<<"$sql")
    elif [[ -n $mids ]]; then
        sql=$(sed "s/where/& n.mid in ($mids)/" <<<"$sql")
    else
        sql=$(sed '/where/d' <<<"$sql")
    fi
    sqlite3 -json "$database" "$sql" | \
    jq -scM --argjson html "$keep_html" --argjson subdeck "$add_subdeck" '
        def hextonum:
            ascii_downcase | sub("^0x"; "") | explode |
            reduce .[] as $c (0; . * 16 + if $c >= 48 and $c <= 57 then $c - 48 else $c - 87 end);
        (.[0][0].decks | fromjson | with_entries(.value |= .name)) as $dk |
        (.[0][0].models | fromjson | with_entries(.value |= {name,fields: (.flds | map(.name))})) as $ml |
        .[1] | map(.mid |= tostring | .flds |= (
            if $html == 1 then . else
                gsub("<style\\b[^>\u001f]*>[^<\u001f]*</style>"; ""; "i") |
                gsub("<br\\b[^>\u001f]*>"; "\n"; "i") |
                gsub("(?<c>^|\\O)<li\\b[^>\u001f]*>"; (.c |
                    if . == "" then .
                    elif . == "\n" then .
                    elif . == "\u001f" then .
                    else . + "\n"
                    end + "\u2022 "
                ); "i") |
                gsub("<img\\b[^>\u001f]*\\bsrc=(?<q>[\u0022\u0027])(?<src>[^>\u001f\u0022\u0027]*)\\k<q>[^>\u001f]*>"; "[image:\(.src)]"; "i") |
                gsub("<[^>\u001f]*>"; "") |
                gsub("&(?<ent>#?\\w+);"; .ent | ascii_downcase |
                    if   . == "quot" then "\u0022"
                    elif . == "apos" then "\u0027"
                    elif . == "nbsp" then " "
                    elif . == "lt"   then "<"
                    elif . == "gt"   then ">"
                    elif . == "amp"  then "&"
                    elif test("^#\\d+$")  then sub("^#"; "")  | tonumber | implode
                    elif test("^#x\\h+$") then sub("^#x"; "") | hextonum | implode
                    else . end)
            end | split("\u001f")
        ) | .dids |= split(",")) |
        reduce .[] as $n ({};
            .[$ml[$n.mid].name] |= (
                .fields = [
                    if $subdeck == 1
                    then "subdeck"
                    else empty end] + $ml[$n.mid].fields |
                .facts += [[
                    if $subdeck == 1
                    then $n.dids | map($dk[.]) | sort[0]
                    else empty end] + $n.flds]
            )
        )
    '
}

do_csv_out() {
    local factfile mlnames model
    newtemp facts.json && factfile=$newtemp
    get_facts > "$factfile"
    readarray -t mlnames < <(jq -r 'keys_unsorted[]' "$factfile")
    for model in "${mlnames[@]}"; do
        { jq -r --arg model "$model" '
            .[$model] |
            (.fields | @csv),
            (.facts[] | @csv)
        ' "$factfile"
        ((to_stdout)) && echo
        } | send_out csv "$model"
    done
    rmtemp "$factfile"
}

do_json_compact() {
    if ((separate)); then
        newtemp facts.json && local factfile=$newtemp
        get_facts > "$factfile"
        readarray -t mlnames < <(jq -r 'keys_unsorted[]' "$factfile")
        for model in "${mlnames[@]}"; do
            jq -cM --arg model "$model" '.[$model]' "$factfile" \
            | send_out json "$model"
        done
        rmtemp "$factfile"
    else
        get_facts | send_out json
    fi
}

do_json_verbose() {
    local verbify
    read -rd '' verbify <<'END'
    .fields as $flds |
    .facts | map(
        [ $flds, . ] | transpose |
        reduce .[] as $pair ({}; .[$pair[0]] = $pair[1]) )
END
    if ((separate)); then
        newtemp facts.json && local factfile=$newtemp
        get_facts > "$factfile"
        readarray -t mlnames < <(jq -r 'keys_unsorted[]' "$factfile")
        for model in "${mlnames[@]}"; do
            jq -cM --arg model "$model" '.[$model] | '"$verbify" "$factfile" \
            | send_out json "$model"
        done
        rmtemp "$factfile"
    else
        get_facts | jq -cM "map_values($verbify)" | send_out json
    fi
}

do_json_dump() {
    newtemp media.json && local media=$newtemp
    unzip -p "$in_file" media > "$media"
    sqlite3 -json "$database" "
        select * from col;
        select * from notes;
        select * from cards;
        select * from revlog;
        select * from graves;
    " | jq -scM --slurpfile media "$media" '
        {col: .[0][0], notes: .[1], cards: .[2], revlog: .[4], graves: .[5], media: $media[0]} |
        .col |= ( del(.id) | .conf |= fromjson | .models |= fromjson |
            .decks |= fromjson | .dconf |= fromjson | .tags |= fromjson ) |
        .notes |= map(.data |= if length > 0 then fromjson else . end | .flds |= split("\u001f")) |
        .cards |= map(.data |= if length > 0 then fromjson else . end)
    ' | send_out json
    rmtemp "$media"
}

#-- main ---------------------------------------------------

# extract database
newtemp sqlite && database=$newtemp
unzip -p "$in_file" collection.anki21 > "$database"

# option -l redirects stdout to the $less_file
if ((to_less==1)); then
    if [[ -t 1 ]]; then
        newtemp less && less_file=$newtemp
        exec 3>&1 > "$less_file"    # saves orig stdout in &3
        to_less=2
    else
        to_less=0
    fi
fi

# get the set of deck ids -d and model ids -m if specified
if ((${#decks[@]})); then
    decks=($(printf '%s\n' "${decks[@]}"  | sort -nu))
    max_deck=${decks[-1]}
    num_decks=$(count_decks)
    ((max_deck>num_decks)) && die "There are only $num_decks decks, so -d $max_deck is out of range"
    dids=$(get_dids)
fi
if ((${#models[@]})); then
    models=($(printf '%s\n' "${models[@]}"  | sort -nu))
    max_mod=${models[-1]}
    num_mods=$(count_models)
    ((max_mod>num_mods)) && die "There are only $num_mods models, so -m $max_mod is out of range"
    mids=$(get_mids)
fi

# mode dispach
if ((text_info)); then
    do_text_info
elif ((json_info)); then
    do_json_info
elif ((csv_out)); then
    do_csv_out
elif ((json_compact)); then
    do_json_compact
elif ((json_verbose)); then
    do_json_verbose
elif ((json_dump)); then
    do_json_dump
else
    die "Unknown mode (missing implementaion, or a bug)"
fi

# tidy up database temp file
rmtemp "$database"

if ((to_less)); then
    # restore orig stdout, run less, tidy temp file
    exec >&3 3>&-
    less -R "$less_file"
    rmtemp "$less_file"
fi

